#ifndef REMOTE_CONTROLLER_RASPI_SETTINGS_HPP
#define REMOTE_CONTROLLER_RASPI_SETTINGS_HPP

// TCP settings
#define TCP_HOST_IP_ADDRESS "192.168.49.1" //"192.168.178.177" //todo: get it automatically
#define TCP_HOST_PORT 8080

// Solenoid settings
#define PIN_SOLENOID 1 //BCM 18
#define SOLENOID_ACTIVE_STATE HIGH

// Stepper motor settings
#define STEPPER_MOTOR_DELAY_1 800 // in us
#define STEPPER_MOTOR_DELAY_2 800 // in us
#define STEPPER_MOTOR_STEP_RATIO 12
#define PIN_STEPPER_MOTOR_DIR 5 //BCM 24
#define PIN_STEPPER_MOTOR_STEP 3 //BCM 22
#define PIN_STEPPER_MOTOR_ENABLE 0 //BCM 17

#endif //REMOTE_CONTROLLER_RASPI_SETTINGS_HPP